name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: prem-minister/podcast-generator@main
